### ISSUE TITLE
Batterfly

### ISSUE THREAD

**Issue by regob** [Veradictus/Kaetram-Open#7]
Not Batterfly, Butterfly.

**Comment by lemueldls** [comment]
Hello @regob, this isn't a typo but a feature. It’s an intended misspell such as other mobs like the *Molar Bear, Snek, Spooder, Fesh, and Chul*.

**Comment by regob** [comment]
Oh, sorry then.

**Comment by regob** [comment]
I realized it is really more like a bat than a butterfly :D
