### ISSUE TITLE
In items.json, The Pickle item has no defense value and the WoodenBow has 0 attack

### ISSUE THREAD

**Issue by ddq1** [Veradictus/Kaetram-Open#9]
"Pickle": {
    "id": 259,
    "type": "armor",
    "name": "Pickle Armour"
  }

  "WoodenBow": {
    "id":87,
    "type":"weaponarcher",
    "attack":0,
    "name":"Wooden Bow"
  },

**Comment by Veradictus** [comment]
Pickle armour will most likely be used as a cosmetic, so I’m not sure if stats are necessary.
